GET http://localhost:4004/odata/v4/CatalogService/businesspartner HTTP/1.1

###

GET http://localhost:4004/odata/v4/CatalogService/address/7554a050-c6ea-426d-ab17-1791fdc7dd
###

POST http://localhost:4004/odata/v4/CatalogService/businesspartner HTTP/1.1
Content-Type: application/json

{
    "NODE_KEY": "4aad1e3b-a70a-4a26-9521-5990f3519a55",
    "BP_ROLE": 1,
    "EMAIL_ADDRESS": "test@yahoo.com",
    "PHONE_NUMBER": "5436534",
    "FAX_NUMBER": "465354",
    "WEB_ADDRESS": "www.hello.com",
    "BP_ID": 11223,
    "COMPANY_NAME": "Kickers"
}

###
PUT http://localhost:4004/odata/v4/CatalogService/businesspartner/4aad1e3b-a70a-4a26-9521-5990f3519a55 HTTP/1.1
Content-Type: application/json

{
    "EMAIL_ADDRESS": "sap-user@test.com",
    "PHONE_NUMBER": "12345679"
}

###
POST http://localhost:4004/odata/v4/CatalogService/worker HTTP/1.1 
Content-Type: application/json 

{    
      "firstName": "Erwin",
      "lastName": "Mcraig",
      "Gender": "M",
      "phoneNumber": "+91-9652143258",
      "email": "erwin_pogi@yahoo.com",
      "currency_code": "USD",
      "salaryAmount": 34346
}